### ISSUE TITLE
cameraIdel is not defined 문제가 간헐적으로 발생합니다.

### ISSUE THREAD

**Issue by whdals0** [johyunchol/kakao_map_plugin#12]
안녕하세요. kakao_map_plugin을 사용하려고 합니다.

그런데, 가끔 맵을 띄우다 보면

I/chromium(29467): [INFO:CONSOLE(169)] "Uncaught ReferenceError: cameraIdle is not defined", source: about:blank (169)

위와같은 오류가 발생하면서 카카오맵의 동작이 멈추는 현상이 발생됩니다.
앱은 정상적으로 다른 버튼들이 동작하는데, 카카오맵의 기능들(맵 이동, 확대 축소, 마커 클릭 등)이 멈춥니다.

```dart
KakaoMap(
              onCameraIdle: ((pos, zoomLevel) {
                selectLatLng = pos;
                print('지도 레벨은 $zoomLevel 이고');
                print(
                    '중심 좌표는 위도 ${pos.latitude},\n경도 ${pos.longitude} 입니다');
                markers.clear();
                mapController.clearMarker();
                markers.add(Marker(
                  markerId: UniqueKey().toString(),
                  latLng: pos,
                  offsetY: 16,
                ));
                mapController.addMarker(markers: markers.toList());
              }),
              onMapCreated: ((controller) async {
                mapController = controller;
                selectLatLng = await mapController.getCenter();
                markers.add(Marker(
                  markerId: UniqueKey().toString(),
                  latLng: selectLatLng,
                  offsetY: 16,
                ));
                mapController.addMarker(markers: markers.toList());
                  setState(() {});
              }),
              currentLevel: 4,
              center: LatLng(latitude, longitude),
            ),
``` 
위처럼 사용을 하고 있습니다.

카카오 맵 센터의 좌표값을 구하기 위해서 여러 함수를 사용해보았습니다.

onDragChangeCallback,   onCameraIdle,  onCenterChangeCallback 함수를 모두 붙여보았는데, 
모두 동일한 현상이 발생합니다.

지연시간 문제인가 싶어 맵 로딩후 3초이상 기다렸다가도 해보았습니다.

맵을 처음에 로드할 때는 문제가 없다가, 위의 함수들이 호출되는 시점(맵을 드래그 하고 놓는 순간) 에 
Uncaught ReferenceError : {함수이름} is not defined 가 발생합니다.

이 부분을 어떻게 해결할 수 있을까요?

**Comment by johyunchol** [comment]
이부분은 라이브러리 코드단에 확인이 필요할거 같네요. 확인 후 답변 드리도록 하겠습니다!

**Comment by johyunchol** [comment]
최근에 바쁜 일정때문에 답변이 늦었습니다.
저 도 비슷한 현상이 있어서 확인 해 보니 callback 을 받는 코드가 html load 코드 보다 뒤쪽에 선언되다 보니 처음 로딩 시 함수를 찾지 못하는 경우가 있더라구요.

해당 이슈 해결하여 0.1.9 버전 업데이트 하였습니다!

**Comment by whdals0** [comment]
> 최근에 바쁜 일정때문에 답변이 늦었습니다. 저 도 비슷한 현상이 있어서 확인 해 보니 callback 을 받는 코드가 html load 코드 보다 뒤쪽에 선언되다 보니 처음 로딩 시 함수를 찾지 못하는 경우가 있더라구요.
> 
> 해당 이슈 해결하여 0.1.9 버전 업데이트 하였습니다!

빠른 피드백 감사합니다!!

**Comment by johyunchol** [comment]
해당 이슈는 해결된거로 보고 close 하도록 하겠습니다!
