### ISSUE TITLE
customOverlays에 xAnchor, yAnchorx 추가

### ISSUE THREAD

**Issue by cyseo99** [johyunchol/kakao_map_plugin#13]
customOverlays위치를 조정하고 싶은데 
customOverlays에 xAnchor, yAnchor가 없어서 좌표값으로 움직일까 했지만 그렇게 하면 zoom레벨에 따라 이상하게 움직입니다
추가해주실수 있으실까요 ㅠㅠ

**Comment by johyunchol** [comment]
확인해 보니 제가 해당값(xAnchor, yAnchor)을 고정값으로 해두었었네요.

`
        let customOverlay = new kakao.maps.CustomOverlay({
            map: map,
            clickable: isClickable,
            content: content,
            position: markerPosition,
            xAnchor: 0.5,
            yAnchor: 1,
            zIndex: 3
        });
`

이부분은 zIndex 를 포함하여 전달받은 값으로 사용할 수 있도록 처리 하도록 하겠습니다.

**Comment by johyunchol** [comment]
0.2.1 버전에서 해당 부분 추가 해 두었습니다.

overlay_21_custom_overlay1_screen.dart

파일을 보시면 xAnchor, yAnchor, zIndex 를 추가 하는 방법에 대해 예시를 작성 해 두었으니 확인 해 보시면 됩니다!

해결된 것으로 보고 해당 이슈는 닫도록 하겠습니다. 혹시나 같은 이슈 발생시 이슈  reopen 해주세요!
