### ISSUE TITLE
안드로이드 카카오맵 실행이 안 되는 이슈

### ISSUE THREAD

**Issue by yangsh91** [johyunchol/kakao_map_plugin#14]
ios에서는 정상동작하는데 안드로이드에서 맵이 실행이 안 되는 이슈가 있습니다

그냥 흰화면만 나오길래 로딩이 오래걸리는건가 싶었는데 로그를 확인해 봤을때

I/chromium(32434) : [INFO:CONSOLE(22)] "Uncaught TypeError : kakao.maps.latLng is not a constructor", source: about:blank (22)
와 같이 뜨는거 같은데 manifest에 설정한 내용 말고 추가로 세팅해줘야할 내용이 있을까요?

**Comment by heyphat** [comment]
I have the same issue, please help!

**Comment by heyphat** [comment]
Oh, I found it, I forgot this line.
https://github.com/johyunchol/kakao_map_plugin/blob/3060e8c9ea0695864071e3c90bcf724c8ec183cb/example/lib/main.dart#L7

**Comment by johyunchol** [comment]
해당 이슈 확인이 늦었습니다. 

혹시 흰 화면만 나온다고 하시는게 example 소스 인지, 아니면 직접 구현한 소스 인지 궁금합니다.
추가적으로 flutter version까지 말씀 해 주시면 확인 해볼 수 있을거 같습니다.

**Comment by alswn2348** [comment]
저는 mainfest에 usesCleartextTraffic = true 가 적용이 안됬었을때 같은 이슈를 경험했습니다 적용후에는 잘 됩니다!

**Comment by johyunchol** [comment]
@alswn2348 님 감사합니다! 해당 이슈는 close 처리 하도록 하겠습니다.
혹시 같은 이슈가 발생하면 이슈 repoen 해주세요!
