### ISSUE TITLE
마커 클러스터링 업데이트

### ISSUE THREAD

**Issue by cyseo99** [johyunchol/kakao_map_plugin#15]
안녕하세요 항상 감사히 사용중입니다.
 
마커 클러스터링 업데이트는 혹시 언제쯤 예상 하시나요?

**Comment by johyunchol** [comment]
안녕하세요! 마커 클러스터링에 대한 부분은 사용하시는 분이 따로 없는거 같아 구현해 놓지 않았었습니다.

요청하셨으니 추가로 개발 진행 하도록 하겠습니다!

**Comment by cyseo99** [comment]
감사합니다!

**Comment by Kor-YJ** [comment]
안녕하세요! @johyunchol  혹시 마커 클러스터 업데이틑 됐나요?>??

**Comment by johyunchol** [comment]
아쉽게도 아직 클러스터 기능 업데이트를 못했습니다. ㅠㅠ

간단하게 될 줄 알았는데 여러가지로 시도 해보곤 있지만 정상동작을 안하고 있어서요...

**Comment by Kor-YJ** [comment]
@johyunchol  아쉽네요 ㅠㅠ 지금 카카오맵 플러터로 해보고 있는데 너무 잘 만드셔서 편하게 잘 쓰고 있어요 감사합니다 !

**Comment by johyunchol** [comment]
@cyseo99 @Kor-YJ 

마커 클러스터링 기능에 0.2.3 버전에서 추가되었습니다!

**Comment by cyseo99** [comment]
감사합니다!!
