### ISSUE TITLE
마커 위치에 대해서 문의드립니다.

### ISSUE THREAD

**Issue by softgi** [johyunchol/kakao_map_plugin#16]
markerImageSrc에 base64이미지나 이미지 url을 넣으면 zoom이 축소될수록 마커위치가 대각선 아래로 갑니다.
markerImageSrc에 아무것도 넣지 않았을때는 정상으로 작동합니다.
카카오에서 제공해주는 http://t1.daumcdn.net/localimg/localimages/07/2018/pc/img/marker_spot.png 다음 이미지 파일을 넣어도 동일합니다.
이유를 알 수 있을까요?

버전은 0.2.1을 사용중입니다.

**Comment by johyunchol** [comment]
재현을 해보려고 하는데 해주신 말이 잘 이해가 안가는 부분이 있습니다.

"축소될수록 마커위치가 대각선 아래로 갑니다"

**Comment by softgi** [comment]
<img width="394" alt="image" src="https://github.com/johyunchol/kakao_map_plugin/assets/86591934/21f07342-7a70-4135-a778-eff97b3f3ee1">
이게 markerImageSrc에 아무것도 넣지 않았을때 이미지입니다.

<img width="402" alt="image" src="https://github.com/johyunchol/kakao_map_plugin/assets/86591934/d3055ad5-3056-4576-b2df-c955a4b6e5bd">
markerImageSrc에 카카오에서 제공하는 img url = http://t1.daumcdn.net/localimg/localimages/07/2018/pc/img/marker_spot.png
다음을 넣었을때인데 다른 url을 적용해도 대구쪽을 보면 마커위치가 다른게 보입니다.

**Comment by castlehoon** [comment]
점점 확대하면 마커위치가 조금씩 정상 자리로 잡히는데 url로 넣었을때 아이콘 이미지 영역이나 시작 위치쪽이 맞지않는듯합니다.

**Comment by softgi** [comment]
점점 확대하면 마커위치가 조금씩 정상 자리로 잡히는데 url로 넣었을때 아이콘 이미지 영역이나 시작 위치쪽이 맞지않는듯합니다.

**Comment by johyunchol** [comment]
이부분이 원래 카카오의 javascript 소스가 그런지, 라이브러리로 변환하면서 발생한 문제인지 확인 해 보고 답변 드리도록 하겠습니다.

**Comment by softgi** [comment]
대구뿐만 아니라 모든 좌표에 동일한 문제가 발생하고 있습니다.

**Comment by johyunchol** [comment]
최종적으로 확인 해 보니 offsetX, offsetY 를 입력하지 않으면 0 으로 세팅 되도록 되어 있어서 발생하는 이슈 였습니다.

이 부분 해결하여 0.2.2 버전 업데이트 하였습니다!

**Comment by softgi** [comment]
네 감사합니다~!
