### ISSUE TITLE
Long Press 이벤트 추가

### ISSUE THREAD

**Issue by skult82** [johyunchol/kakao_map_plugin#2]
웹뷰에서 Long Press 이벤트를 감지해서, Long Press 한 터치포인트의 위치와 GPS 데이터를 콜백으로 전달해주면 좋겠습니다.

**Comment by johyunchol** [comment]
웹뷰에서 LongPress 를 감지 하기 보다는 document 에서 addEventListener 에서 touchstart, touchend 를 감지하여 LongPress 를 감지할 수 있을 것 같긴 합니다.

다만 안드로이드 웹뷰에서는 touch 한 position 이 초기화 되는 이슈가 있는듯 합니다. 또 혹시 카카오에서 longpress 를 제공하는지 확인해보았는데 event 를 제공하고 있지 않아서 당장 해결하기가 어려워 보이기도 합니다.

다른 해결방안이 있는지는 더 찾아봐야될 것 같습니다.

**Comment by skult82** [comment]
저도 확인해보니 네이티브 라이브러리인 경우에는 제공을 하지만, 자바스크립트 라이브러리에서는 제공하지 않음을 확인하였습니다.
아마도 자바스크립트 라이브러리는 PC 사용자를 대상으로 했기 때문이지 않을까 생각이 됩니다.

혹시라도 나중에 개발을 진행하실 때 아래의 저장소가 도움이 될 수 있지 않을까 하여 링크를 남겨드립니다.

[john-doherty](https://github.com/john-doherty)/[long-press-event](https://github.com/john-doherty/long-press-event)

**Comment by johyunchol** [comment]
남겨주신 링크로 해봤었는데 LongPress 에 대한 감지는 되는데 touch 한 위치의 좌표가 넘어오지 않더라구요.

다른 방법을 찾아보도록 하겠습니다~
