### ISSUE TITLE
center가 좌상단으로 이동합니다.

### ISSUE THREAD

**Issue by mizchaboo** [johyunchol/kakao_map_plugin#22]
center: LatLng(33.450701, 126.570667)
해당 좌표가 지도상에서 좌상단으로 위치합니다.
ios, android 모두 동일합니다.

**Comment by mizchaboo** [comment]
타이머로 시간차를 두고 이동시키니 되는군요

**Comment by johyunchol** [comment]
혹시 해당 현상이 어떻게 발현되는지 동영상 촬영 같은것이 가능할까요? 동영상과 작성하신 코드를 공유해 주시면 어떻게 처리 했는지 확인하고 대응이 가능할거 같습니다!
