### ISSUE TITLE
Is it possible to show user's current location? and listen it

### ISSUE THREAD

**Issue by Lazizbek97** [johyunchol/kakao_map_plugin#24]
Hello,
I am going to show user's current location and it listen. when user moves 'my location' moves accordingly. as any other maps, it is default functionality.
does this plugin supports it?
if not is there any plugins that support it?
Thank you!

**Comment by johyunchol** [comment]
Hello,

Unfortunately, the feature you mentioned is not provided by the Kakao Map API, so we do not offer it separately. However, we will consider the possibility of implementing it and will try to add it if it's feasible.

Thank you.
