### ISSUE TITLE
can we add asset image as marker on map?

### ISSUE THREAD

**Issue by Lazizbek97** [johyunchol/kakao_map_plugin#25]
i have checked examples. but there was one example which supports weblink of image for marker. 
can we add asset image as well? if so, how can we add it?
Thanks

**Comment by johyunchol** [comment]
Hello. I apologize for the delay in my response.

The library I've created currently loads HTML directly on top of a Flutter webview. However, this approach doesn't support adding local asset images easily.

To make it possible, you might consider using the flutter_inappwebview library in your development project to set up a local server and add assets. This approach would allow you to work with local asset images more effectively.

Thank you for your understanding.
