### ISSUE TITLE
CustomOverlay 클릭 이벤트가 최초 로딩된 overlay에만 동작합니다.

### ISSUE THREAD

**Issue by fuzes** [johyunchol/kakao_map_plugin#26]
zoom level을 높였을 때 지도에 새로 표시된 overlay들은 클릭 이벤트가 동작을 안합니다.
수정 해보려고 했는데 쉽지 않네요 ^^;;;

**Comment by johyunchol** [comment]
이부분 수정하여 0.2.4 버전으로 업데이트 하였습니다!

CustomOverlay 의 Click event 같은 경우 kakao map 에서 제공 하는 방식이 아니다 보니 제가 추가 한 기능에서 에러가 있는것을 확인 했습니다. 최신 버전 확인 해 보시고 안되면 말씀 해주세요!
