### ISSUE TITLE
로드맵 이슈

### ISSUE THREAD

**Issue by Baebin** [johyunchol/kakao_map_plugin#28]
안녕하세요.
현재 [0.2.4](https://github.com/johyunchol/kakao_map_plugin/commit/450d018d625f4bdf5e1de42180009d5ef6c0c7d0) 버전을 사용하고 있습니다.
현재 카카오 거리뷰가 정상적인 위치에서 실행되지 않고 특정 지점을 계속해서 로드하는 문제가 발생하고 있습니다.
라이브러리 파일 중 KakaoRoadMap의 내부 코드를 확인해보니 position이 new kakao.maps.LatLng(33.450701, 126.570667)으로 고정되어 있는데, 업데이트해주실 수 있을까요?

**Comment by johyunchol** [comment]
@Baebin 님, 해당 부분 center 값 동적으로 받아서 처리하도록 수정하였습니다.

0.2.6 버전 사용하시면 됩니다!
