### ISSUE TITLE
Stack과 함께 사용시 더 상단에 있는 위젯에서 맵 터치가 됩니다.

### ISSUE THREAD

**Issue by jerryamuz** [johyunchol/kakao_map_plugin#32]
아래의 코드로 해당 문제 확인 가능합니다.
파란색 Container를 빠르게 여러번 터치시 onMapTap의 print가 찍히고 zoom도 작동합니다.
그래서 KakaoMap() 위젯에 IgnorePointer로 감싸보았는데도 터치가 작동합니다.
해결 방법이 있을까요?
좋은 패키지 감사드립니다.

```dart
Stack(
    children: [
      KakaoMap(
        onMapTap: (latLng) {
          print('latLng: $latLng');
        },
      ),
      Positioned(
        left: 0,
        right: 0,
        bottom: 0,
        child: Container(
          color: Colors.blue,
          height: 200,
          width: double.infinity,
        ),
      ),
    ],
  ),
```

**Comment by johyunchol** [comment]
안녕하세요. 답변이 늦어 죄송합니다.

해당 부분은 확인 해보고 답변 드리도록 하겠습니다!

**Comment by johyunchol** [comment]
@jerryamuz 님, 제가 재현해 보기 위해 코드를 추가 하였는데요.

샘플 1번 코드에 KakaoMap 부분을 Stack 으로 감싸서 확인 해 보았습니다.
`
import 'package:flutter/material.dart';
import 'package:kakao_map_plugin/kakao_map_plugin.dart';
import 'package:kakao_map_plugin_example/src/home_screen.dart';

/// 지도 생성하기
/// https://apis.map.kakao.com/web/sample/basicMap/
class Map1DefaultScreen extends StatefulWidget {
  const Map1DefaultScreen({Key? key, this.title}) : super(key: key);

  final String? title;

  @override
  State<Map1DefaultScreen> createState() => _Map1DefaultScreenState();
}

class _Map1DefaultScreenState extends State<Map1DefaultScreen> {
  late KakaoMapController mapController;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title ?? selectedTitle),
      ),
      body: Stack(
        children: [
          KakaoMap(
            onMapTap: (latLng) {
              print('latLng: $latLng');
            },
          ),
          Positioned(
            left: 0,
            right: 0,
            bottom: 0,
            child: Container(
              color: Colors.blue,
              height: 200,
              width: double.infinity,
            ),
          ),
        ],
      ),
    );
  }
}
`

그런데 아래 영상과 같이 해당 현상 재현이 안되는데 아직도 같은 현상이 발생할까요?

https://github.com/johyunchol/kakao_map_plugin/assets/3314683/647ef869-e38a-450e-8fe5-ccdd37f98cf9

**Comment by johyunchol** [comment]
더이상 답변이 없어서 이슈를 닫습니다!
