### ISSUE TITLE
resumed -> active 로 변경하면 화면이 안나옵니다.

### ISSUE THREAD

**Issue by jieun8206** [johyunchol/kakao_map_plugin#33]
지도화면 실행해 놓고, AppLifecycleState.resumed 상태 즉 다른 어플리케이션 실행 후,
수분 후~
다시 본 지도화면으로 돌아오면 지도화면이 안나옵니다.

테스트는 패키지내 example 로 해봤습니다.

지도 나오게 갱신할수 있는 방법이 있을까요?

setState{()} 또는
await _mapController.webViewController.clearCache();
await _mapController.webViewController.reload();
써봐도 사라진 지도 화면은 다시 나오지 않네요.

**Comment by johyunchol** [comment]
안녕하세요. 최근에 일이 바빠서 확인이 늦었습니다.

이부분은 재현을 해보고 처리 가능하면 처리 하도록 하겠습니다.

**Comment by jieun8206** [comment]
android14 에서 문제가 되는것 같네요.

**Comment by johyunchol** [comment]
@jieun8206 님 혹시 말씀해 주신 

다른앱 에서 수분 후 다시 돌아왔을때 지도가 안나온다고 하신 부분에서 

수분이 혹시 5분정도만에도 재현이 될까요? 아니면 더 오래 기다려야 할까요?

**Comment by jieun8206** [comment]
android14 OneUI 6.1버전 업데이트 하면서 해당 문제 사라 졌습니다.

**Comment by johyunchol** [comment]
일단 이 이슈는 닫도록 하겠습니다! 추 후 같은 이슈 반복되면 reopen 부탁 드립니다.
