### ISSUE TITLE
Flutter Web 프로젝트에서 사용하려고 합니다.

### ISSUE THREAD

**Issue by nask-duck** [johyunchol/kakao_map_plugin#34]
```
class TestView extends GetView<TestController> {
  const TestView({super.key});

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      body: KakaoMap(),
    );
  }
}

class TestController extends GetxController {
}
```

Flutter Web 프로젝트 중에 카카오맵을 쓰려고 해서 테스트를 하는 중이였습니다.

TestView로 이동을 하였는데 아래의 에러가 발생을 해서 도움받으려고 남깁니다.

![image](https://github.com/johyunchol/kakao_map_plugin/assets/106095497/10f93089-9900-4ed5-900b-f7c8929f8dd2)

아래는 dependencies 정보입니다
-pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  gap: ^3.0.1
  logger: ^2.0.3
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  carousel_slider: ^4.2.1
  kakao_map_plugin: ^0.2.5

**Comment by johyunchol** [comment]
안녕하세요. 아쉽지만 현재 해당 라이브러리는 Web 으로 제공 되지 않고 있습니다.

WebView 를 이용해서 라이브러리를 만든 것이긴 한데 해당 WebView 가 android, ios 만 지원하고 있다보니 web은 별도로 구현이 필요한 상황입니다.

아쉽지만 지금은 직접 구현하셔야 할 것 같습니다 ㅠㅠ
