### ISSUE TITLE
카카오 맵에 마커의 우선순위를 지정할 수 있을까요?

### ISSUE THREAD

**Issue by kindkmj** [johyunchol/kakao_map_plugin#36]
같은 곳에 마커가 생기면 우선순위를 지정해서 z index? 를 설정하여 어느 마커가 높게 그려질지 정할 수 있을까요?...

또한 여러 포지션의 중앙지점으로 카메라를 이동시키는...그러한 기능이 될까요?

**Comment by kindkmj** [comment]
마커는 늦게 생성한게 z인덱스 우선순위가 높게 되는거네요!

**Comment by johyunchol** [comment]
@kindkmj 님,

아마 전체적으로 늦게 생성된게 우선순위가 높긴 할건데요.
현재는 CustomOverlay 에만 zIndex 를 직접 세팅할 수 있도록 되어 있습니다. 마커등 다른 곳에도 추가 해 놓도록 하겠습니다!

여러 포지션의 중앙지점으로 카메라 이동 관련한 부분은 fitBounds 를 말씀하시는 것 같은데 구현은 되어 있습니다.
[예제 소스는 여기]보시면 됩니다.(https://github.com/johyunchol/kakao_map_plugin/blob/main/example/lib/src/map_14_region_reset_screen.dart)

**Comment by johyunchol** [comment]
@kindkmj 님, 마커 및 polyline, polygon, circle 등 전체적으로 zIndex 를 설정할 수 있도록 수정하였습니다.

0.2.6 버전 사용하시면 됩니다!
