### ISSUE TITLE
Uncaught ReferenceError: kakao is not defined 

### ISSUE THREAD

**Issue by kindkmj** [johyunchol/kakao_map_plugin#37]
갤럭시 노트 10 + 
안드로이드 12 
에서 빌드시에 에러 메시지가 발생합니다.

**Comment by johyunchol** [comment]
javascript 키 이슈 인듯 한데요.

https://ldgeao99-developer.tistory.com/553 여기 참고 해 보시면 될 것 같습니다!

**Comment by kindkmj** [comment]
감사합니다.
같은 프로젝트 로 빌드시
특정 기기의 이슈는 아니라고 생각하지만
갤럭시 노트10 안드12버전
갤럭시 s22 안드14? 버전
에서 갤럭시 노트10 에서만 해당 이슈가 발생해서요 ㅜ

**Comment by johyunchol** [comment]
@kindkmj 혹시 어떻게 api key 를 넣으셨는지 코드를 공유 해 주실 수 있으신가요?

**Comment by kindkmj** [comment]
main 부분에
// AuthRepository.initialize(appKey: 'key');
형태로 첨부했습니다.

**Comment by johyunchol** [comment]
@kindkmj 

`.env` 를 사용하신건 아니고 appKey 에 string 으로 바로 넣으신거가 맞을까요?

**Comment by kindkmj** [comment]
네 맞습니다 따로 env환경은 없어서 키를 바로 등록했습니다.

**Comment by johyunchol** [comment]
@kindkmj 

저도 여러기기 테스트 해보겠지만... 일단 특정 상황이 재현되면 알려주시면 저도 한번 더 해보도록 하겠습니다!
