### ISSUE TITLE
Library5AddressToCoordsScreen 예제에서 final response = await mapController.coord2Address(request); 문제

### ISSUE THREAD

**Issue by gotlr98** [johyunchol/kakao_map_plugin#38]
33번 line에 final response = await mapController.coord2Address(request); 
호출된 이후 코드가 실행이 안되는데 혹시 확인 가능할까요??

**Comment by johyunchol** [comment]
해당 이슈에 대한 답변이 늦어서 죄송합니다.

@Dokyeongyun 님께서 해당 이슈에 대한 PR 을 올려주셔서 머지 후 배포 하였습니다.

[https://pub.dev/packages/kakao_map_plugin/versions/0.3.1](https://pub.dev/packages/kakao_map_plugin/versions/0.3.1)
0.3.1 버전을 업데이트 했으니 확인 하실 수 있습니다.
