### ISSUE TITLE
Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript

### ISSUE THREAD

**Issue by gotlr98** [johyunchol/kakao_map_plugin#41]
Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., A JavaScript exception occurred (WKErrorDomain:4:{WKJavaScriptExceptionLineNumber: Unsupported Type: 1, WKJavaScriptExceptionMessage: ReferenceError: Can't find variable: clearMarker, WKJavaScriptExceptionSourceURL: Unsupported Type: undefined, NSLocalizedDescription: A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber: Unsupported Type: 12}), null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1167:7)
<asynchronous suspension>
#1      WebKitWebViewController.runJavaScript (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:462:7)
<asynchronous suspension>

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

맵이 생성될 때 이런 에러가 발생하는거 같은데 확인 부탁드립니다

**Comment by johyunchol** [comment]
@gotlr98 안녕하세요.

Android, iOS 중 어떤 플랫폼으로 빌드하신 걸까요? 
javascript key 입력이나 Android, iOS 에서 설정해 주어야 할 부분을 설정했는데도 같은 현상일까요?

**Comment by gotlr98** [comment]
넵 ios로 빌드했고 설정 다 했는데, 맵은 생성되는데 에러 메세지가 계속 나옵니다

**Comment by gotlr98** [comment]
더불어 원래 Drawer close 후에 마커를 설정해주면 메인맵에 마커가 잘 나왔었는데, 저 오류가 나온후 부터인지는 모르겠으나 지금 setState를 해주었음에도 불구하고 마커가 표시안되는것 같습니다.

**Comment by johyunchol** [comment]
@gotlr98 님, 제 아이폰에 빌드 해 봤을 때는 정상이다 보니 코드 확인이 필요할 듯 한데요.

혹시 작성한 코드를 공유해 주실 수 있으실까요?

**Comment by gotlr98** [comment]
https://github.com/gotlr98/MatJang/blob/main/matjang/lib/pages/MainMap.dart
MainMap.dart에 메서드와 지도가 포함되어있습니다!

**Comment by johyunchol** [comment]
@gotlr98 님, 

해당 코드에 Stack 으로 UI 가 쌓여 있다보니 혹시나 지도가 생성 되었지만 안나오는건 아닐지도 확인이 필요 한데요. 
혹시 새로운 페이지를 생성하고 scafoold body에 KakaoMap 만 로드했을때도 같은 현상인지 확인이 필요할 거 같습니다.

만약 동일한 증상이라면 Android 로 빌드했을 때도 같은지도 봐야 하구요.

그리고 main.dart 에서 AuthRepository.initialize 할 때 .env 파일 내부에서 APP_KEY 와 BASE_URL 은 잘 불러와지는지 확인이 필요할것 같습니다.

**Comment by gotlr98** [comment]
아 해결했습니다
WidgetsBinding.instance.addPostFrameCallback()
안에 setState 메서드에서 오류가 발생했었습니다
신경써주셔서 감사합니다

**Comment by johyunchol** [comment]
잘 해결 되어 다행이네요!
