### ISSUE TITLE
클러스터 리셋 문의

### ISSUE THREAD

**Issue by jihh77** [johyunchol/kakao_map_plugin#44]
안녕하세요!

먼저 꿀 같은 패키지를 만들어주신 제작자님께 정말 감사하다는 말씀을 올리면서
문의를 살짝 남겨봅니다!
(저 같은 앱 개발 초짜에겐 진짜 지리산 토종 벌꿀 같은 패키지에욥!!)

제가 지금
1. 지도에 마커, 클러스터를 생성
2. 변경된 위치에서 재검색
3. 기존 마커,클러스터를 삭제하고 새로운 마커, 클러스터 만들기

를 하려고 하는데

3. 기존 마커, 클러스터 삭제하는 방법을 모르겠어요.. 흑흑

하나님, 부처님, 알라신님 알려주세요! 

그럼 오늘도 신명나는 하루 되세요~

=====================================
찾아보니 
        mapController?.clearMarker();
        mapController?.clearMarkerClusterer();

로 간단하게 해결이 되는거였네요?!
뻘글이었습니닷!

**Comment by johyunchol** [comment]
아 해결 되었다니 다행이네요! 라이브러리 잘 사용해 주셔서 감사합니다~

다른 이슈 발생하면 언제든 이슈 남겨 주세요!

해당 이슈는 close 처리 하도록 하겠습니다!
