### ISSUE TITLE
Controller dispose() 방법

### ISSUE THREAD

**Issue by hymi54** [johyunchol/kakao_map_plugin#45]
KakaoMapController 사용 후 dispose시 명시적으로 dispose()하려고 하는데 메서드가 없네요. 명시적으로 dispose()하는 다른 방법이 있을까요?

**Comment by johyunchol** [comment]
혹시 어떤 형태에서 dispose 를 사용하실 계획이실까요?

한 위젯에서 KakaoMapController 를 보여주다가 다른 화면으로의 전환을 위해 해당 위젯에서 명시적으로 map 을 제거 하고 싶으셔서 그러신 걸까요?

[카카오 API Document](https://apis.map.kakao.com/web/documentation/)

위 문서에서는 명시적으로 map 객체를 clear 하는게 없다보니 객체를 null 처리 해주면 될 것으로 예상되기는 합니다.
원하시는 기능에 따라 해당 라이브러리에 dispose 함수를 만들고 내부에서 map 객체를 null 처리 해주면 되겠지만 필요한 상황이 어떤 상황인지 알면 좋을 것 같아 문의 합니다!

**Comment by hymi54** [comment]
네 맞습니다! 다른 화면 전환시 명시적으로 제거하고 싶어서 문의드렸어요. dispose 함수를 만들어주시면 감사드리겠습니다. 좋은 패키지 항상 감사드려요!

**Comment by johyunchol** [comment]
@hymi54 님, 
해당 부분 dispose 추가하여 0.3.2 버전 업로드 하였습니다.

이슈는 닫겠습니다. 혹시나 잘 안되면 다시 이슈 열어주세요.
