### ISSUE TITLE
빌드 시 네임스페이스 관련 오류

### ISSUE THREAD

**Issue by zxcv74720** [johyunchol/kakao_map_plugin#46]
```
A problem occurred configuring project ':kakao_map_plugin'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
```

kakao_map_plugin을 사용하는 프로젝트에서 빌드 시 네임스페이스 관련 오류가 발생합니다.

```
    if (project.android.hasProperty("namespace")) {
        namespace("kr.co.kkensu.kakao_map_plugin")
    }
```

제꺼에선 네임스페이스를 직접 입력함으로써 일단 해결하긴 했는데, 업데이트 해주시나요? 혹시나하고 이슈 올립니다... (초보라서...)

**참고 (야매입니다.)**

<img width="346" alt="스크린샷 2024-10-03 오후 11 03 39" src="https://github.com/user-attachments/assets/ac55285e-1170-4aaa-957d-2f8a395579d6">

네임스페이스 입력은 프로젝트 루트 폴더에서 `External Libraries > Flutter Plugins > Kakao Map Plugins > Android > build.gradle` 에서 안드로이드 중괄호 안에 1번째로 입력하시면 됩니다.

**Comment by johyunchol** [comment]
해당 이슈를 찾아보았더니 AGP 버전이 올라가면서 namespace 를 무조건 작성해야 하는것으로 나오는 것 같습니다. 해당 부분 이슈 해결하여 배포 하도록 할게요!

**Comment by johyunchol** [comment]
@zxcv74720 님, @Zundal 님, 

해당 부분 namespace 추가하여 0.3.2 버전 업로드 하였습니다. 혹시 같은 이슈 발생되면 말씀 해 주세요!
