### ISSUE TITLE
커스텀 마커 생성 문의

### ISSUE THREAD

**Issue by jihh77** [johyunchol/kakao_map_plugin#51]
안녕하세요!

제가 커스텀 마커를 사용해보려고 하는데,
알려주신 예시처럼 마커 이미지 경로를 url로 하면 정상작동 하지만
assets을 사용하면 작동을 안하네요 ㅠㅠ
(url로 쓰다보니 마커가 조금 늦게 찍히는 감이 있어서 assets로 바꿔보려고 합니다)

markerImageSrc: 'https://w7.pngwing.com/pngs/96/889/png-transparent-marker-map-interesting-places-the-location-on-the-map-the-location-of-the-thumbnail.png' (작동 O)

markerImageSrc: 'assets/images/marker_spot.png', (작동 X)

asset 경로는 다른 곳에서도 사용하고 있는 녀석이라 틀리지는 않았습니닷

혹시 커스텀 마커는 url만 작동하는 건가욥??

**Comment by jihh77** [comment]
아 관련해서 이미 답변을 주셨군요 close 처리하겠습니다 ㅎㅎ;

**Comment by johyunchol** [comment]
@jihh77 님 안녕하세요!

제가 문의 주신 내용 관련하여 좀 찾아보았더니 해당 부분의 해결이 가능 할 것으로 보입니다!

flutter 에서 이미지를 base64로 인코딩 후에 javascript 쪽에서 blob 으로 받아서 이미지를 띄우면 가능 할 것 같습니다.

이부분은 테스트를 겨쳐서 반영 하도록 하겠습니다!
