### ISSUE TITLE
lib/src/basic/kakao_map_controller.dart 파일 이슈

### ISSUE THREAD

**Issue by dhbryan75** [johyunchol/kakao_map_plugin#6]
addPolyline 메소드 관련된 코드를 뜯어보던중,
lib/src/basic/kakao_map_controller.dart 37번줄에 clearRectangle이 있어야할것같은데 clearCircle이 있는 것을 발견했습니다.
오타가 맞을까요?

그리고 이것과는 별개로 제가 addPolyline함수로 다른 opacity를 가진 여러개의 polyline들을 추가하려고 하는데 polyline 여러개를 list로 만들어서 addPolyline함수에 전달해도 하나의 polyline만 보여집니다.. 원인이 뭘까요 ㅜㅜㅜ? 

추가) 이런 예외가 뜨고 있었네요
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Result of JavaScript execution returned a `null` value. Use `runJavascript` when expecting a null return value.
#0      WebKitWebViewController.runJavaScriptReturningResult
webkit_webview_controller.dart:416
<asynchronous suspension>
#1      KakaoMapController.addPolyline
kakao_map_controller.dart:15
<asynchronous suspension>
```
추가2) 위의 예외메시지가 시키는대로 runJavaScriptReturningResult를  runJavaScript로 바꾸었더니 하나의 polyline만 보여지던 현상이 해결 되었어요! 수정해서 PR해놓겠습니다 확인해주세요~

**Comment by johyunchol** [comment]
안녕하세요! 버그를 찾아주셔서 감사합니다!

말씀하신대로 lib/src/basic/kakao_map_controller.dart 에서 addRectangle 할 때 clearCircle 대신 clearRectangle 함수를 호출해야 하는게 맞습니다! 해당 부분은 수정해서 배포 하도록 하겠습니다!

추가적으로 addPolyline 할 때 다른 opacity를 가진 여러개의 polyline 들을 추가할 때 에러가 난다고 하셨는데 제가 테스트를 해보니 문제는 찾지 못했습니다. 제가 테스트 한 코드도 함께 배포 해 드릴테니 확인 한 번 같이 해보시면 좋을 듯 합니다.

참고로 제가 코드 작성해서 테스트 해보니 아래 이미지처럼 잘 나왔습니다.

![KakaoTalk_Image_2023-07-08-00-25-02](https://github.com/johyunchol/kakao_map_plugin/assets/3314683/860da9a3-2e62-4d95-9982-79c0de7b7c02)

**Comment by johyunchol** [comment]
0.1.6 버전에서 해결 되어 해당 이슈는 닫습니다! 혹시 문제가 있으면 새로운 이슈를 open 해주세요!

**Comment by dhbryan75** [comment]
이렇게 오픈소스에 pull request 해보는게 처음인데 감사합니다! ㅎㅎ
폴리라인 렌더링 안되던 문제를 저는 ios 시뮬레이터에서 테스트해본 것인데 별로 심각하지 않아보이는 runJavaScriptReturningResult경고를 없애니 해결되는걸 봐서는 시뮬레이터의 문제일 수도 있을 것 같아요

**Comment by johyunchol** [comment]
아마 경고가 나왔던 이슈가 runJavaScriptReturningResult 의 결과를 받아서 사용하지 않아서 그런 듯 보입니다. 최신 버전에서 수정 해 놓았으니 버전 올리시면 될거에요!
