### ISSUE TITLE
Uncaught TypeError: kakao.maps.LatLng is not a constructor"

### ISSUE THREAD

**Issue by clinkchoi** [johyunchol/kakao_map_plugin#8]
개발중인 앱에 적용하고 있는데 다음과 같은 에러가 나고 있습니다.
`I/chromium( 3453): [INFO:CONSOLE(4)] "A parser-blocking, cross site (i.e. different eTLD+1) script, http://t1.daumcdn.net/mapjsapi/js/main/4.4.9/kakao.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://dapi.kakao.com/v2/maps/sdk.js?autoload=true&appkey=hideappkey&libraries=services,clusterer,drawing (4)

I/chromium( 3453): [INFO:CONSOLE(4)] "A parser-blocking, cross site (i.e. different eTLD+1) script, http://t1.daumcdn.net/mapjsapi/js/main/4.4.9/kakao.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://dapi.kakao.com/v2/maps/sdk.js?autoload=true&appkey=hideappkey&libraries=services,clusterer,drawing (4)

I/chromium( 3453): [INFO:CONSOLE(4)] "A parser-blocking, cross site (i.e. different eTLD+1) script, http://t1.daumcdn.net/mapjsapi/js/libs/services/1.0.2/services.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://dapi.kakao.com/v2/maps/sdk.js?autoload=true&appkey=hideappkey&libraries=services,clusterer,drawing (4)

I/chromium( 3453): [INFO:CONSOLE(4)] "A parser-blocking, cross site (i.e. different eTLD+1) script, http://t1.daumcdn.net/mapjsapi/js/libs/clusterer/1.0.9/clusterer.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://dapi.kakao.com/v2/maps/sdk.js?autoload=true&appkey=hideappkey&libraries=services,clusterer,drawing (4)

I/chromium( 3453): [INFO:CONSOLE(4)] "A parser-blocking, cross site (i.e. different eTLD+1) script, http://t1.daumcdn.net/mapjsapi/js/libs/drawing/1.2.6/drawing.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: https://dapi.kakao.com/v2/maps/sdk.js?autoload=true&appkey=hideappkey&libraries=services,clusterer,drawing (4)

I/chromium( 3453): [INFO:CONSOLE(22)] "Uncaught TypeError: kakao.maps.LatLng is not a constructor", source: about:blank (22)`

sdk가 정상적으로 로드가 되지 않은거 같은데 InAppWebView를 이용할때도 마찬가가지로 "Uncaught TypeError: kakao.maps.LatLng is not a constructor" 에러가 납니다.
해결에 도움이 될만한 내용이 있을까해서 문의 드립니다.

참고로

다른앱에서 InAppWebView를 이용하여 Kakaomap이 정상적으로 동작 했었습니다.
문제가 되는 앱에서 InAppWebView에서 GoogleMap으로 했을떄는 정상적으로 표시됩니다.
로그에서appkey는 'hideappkey'로 대체 했습니다.

**Comment by clinkchoi** [comment]
android:usesCleartextTraffic="true"
문제 였습니다.

**Comment by johyunchol** [comment]
아 해결되어서 다행이네요! 혹시 사용하시다가 다른 문제가 발생되면 말씀해주세요!
